from decouple import config

TELEGRAM_BOT1_TOKEN = config('TELEGRAM_BOT1_TOKEN')
TELEGRAM_BOT2_TOKEN = config('TELEGRAM_BOT2_TOKEN')
TELEGRAM_CHAT_ID = config('TELEGRAM_CHAT_ID')
RAPIDAPI_KEY = config('RAPIDAPI_KEY')
